### ISSUE TITLE
그냥 해야할일 목록

### ISSUE THREAD

**Issue by qogusdn1017** [qogusdn1017/monun-docs#2]
1. 라이브러리 문서랑 플러그인 문서 구별

2. 일반 프로그램, 스크립트 문서 구별

~~3. 와 오마이 샌즈 아시는구나~~

~~4. 자 줄서세요 줄서 이렇게하면 오히려 늦어집니다~~

**Comment by qogusdn1017** [comment]
+ https://papermc.io/java16

**Comment by issac4892** [comment]
Github page 활용?

**Comment by qogusdn1017** [comment]
귀찮

**Comment by qogusdn1017** [comment]
...해볼까?

**Comment by qogusdn1017** [comment]
아니 시발근데 예제가 왜 오픈코어 가이드인데 ㅋㅋㅋㅋㅋㅋㅋ

**Comment by issac4892** [comment]
해킨토시는 재밋다

**Comment by qogusdn1017** [comment]
아 꺼지세요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by issac4892** [comment]
님 너무행

**Comment by issac4892** [comment]
https://milooy.wordpress.com/2020/07/28/github-actions%EB%A1%9C-vuepress-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0/

**Comment by issac4892** [comment]
https://issac4892.github.io/ 고장났지만 이렇게 나옴

**Comment by issac4892** [comment]
https://issac4892.github.io/monun-vuepress/ 외이럼

**Comment by qogusdn1017** [comment]
@issac4892 왜 계속 내쪽 빌드실패임

**Comment by issac4892** [comment]
나도 모르겠음

**Comment by issac4892** [comment]
외됨
